import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({
	variable: "--font-primary",
	subsets: ["latin"],
	weight: ["400"]
});

const roboto = Roboto({
	variable: "--font-secondary",
	subsets: ["latin"],
	weight: ["400"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} ${inter.variable}`}>{children}</body>
		</html>
	);
}
